---
image: docker:git

services:
  - docker:dind

before_script:
  - apk update && apk add --no-cache docker
    python3-dev py3-pip docker gcc git curl build-base
    autoconf automake py3-cryptography linux-headers
    musl-dev libffi-dev openssl-dev openssh
  - docker info
  - python3 --version

molecule:
  stage: test
  script:
    - pip3 install ansible molecule docker
    - ansible --version
    # Go to directory containing ansible roles.
    - cd ansible/roles
    # For each directory with an ansible role
    - for dir in *
    - do
          # Go to this directory and test this role
    -     (cd "$dir" && molecule test)
    - done
  only:
    -molecule
