---
- name: "Create user {{ user.login }}"
  user:
    name: "{{ user.login }}"
  register: user_create

- name: "Create home directory for {{ user.login }}"
  user:
    name: "{{ user.login }}"
    create_home: true

- name: "Generate ssh key for {{ user.login }}"
  user:
    name: "{{ user.login }}"
    generate_ssh_key: true
    # Add a comment to the end of ssh key
    ssh_key_comment: "{{ user.email }}"
  when: user_create.changed

- name: "Create group 'wheel'"
  group:
    name: wheel
    state: present
  when: user_create.changed

- name: Allow members of group 'wheel' to execute any command
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
  when: user_create.changed

- name: "Add {{ user.login  }} to the group wheel"
  user:
    name: "[{ user.login  }]"
    # Add user to sudoers
    group: wheel
    append: true
  when: user_create.changed

- name: "Set blank password for {{ user.login }}"
  user:
    name: "{{ user.login }}"
    password: ""
  when: user_create.changed

- name: "Force user {{ user.login }} to change password on first login"
  command: chage -d 0 {{ user.login }}
  when: user_create.changed

- name: "Add {{ user.name }} as GECOS comment"
  user:
    name: "{{ user.login }}"
    comment: "{{ user.name }}"
