---
- name: "Create group 'wheel'"
  group:
    name: wheel
    state: present

- name: Allow members of group 'wheel' to execute any command
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'

- name: "Create user {{ user.login }}"
  user:
    name: "{{ user.login }}"

    create_home: true

    generate_ssh_key: true
    # Add a comment to the end of ssh key
    ssh_key_comment: "{{ user.email }}"

    password: ""
    # Add user to sudoers
    group: wheel
    append: true
    # Add GECOS comment
    comment: "{{ user.name }}"

    state: present
  notify: "Force user {{ user.login }} to change password on first login"
