---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos
    image: centos:7
    priveleged: true
  - name: ubuntu
    image: ubuntu:18.04
    priveleged: true
  - name: archlinux
    image: archlinux/base
    priveleged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    skip-tags: systemd
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
