---
- include_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: install-arch.yml
  when: ansible_os_family == 'Archlinux'

- name: "Set global git name: {{ user.name }}"
  shell: "git config --global user.name \"{{ user.name }}\""
  become: true
  become_user: "{{user.login}}"

- name: "Set global git email: {{ user.email }}"
  shell: "git config --global user.email \"{{ user.email }}\""
  become: true
  become_user: "{{user.login}}"
