---
- include_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: install-debian.yml
  when: ansible_distribution == 'Debian'

- include_tasks: install-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: install-arch.yml
  when: ansible_os_family == 'Archlinux'

- name: "Start and enable 'sshd.service'"
  service:
    name: sshd
    state: started
    enabled: true
