---
- include_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: install-arch.yml
  when: ansible_os_family == 'Archlinux'

- name: "Copy '.tmux.conf' file into '/home/{{ user.login }}/'"
  copy:
    owner: "{{ user.login }}"
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "/home/{{ user.login }}/"
