---
- name: "Clone snapd AUR repository"
  git:
    repo: https://aur.archlinux.org/snapd.git
    dest: /tmp/snapd

- name: "Make snapd AUR package"
  command: "cd /tmp/snapd && makepkg -si"

- name: "Enable the systemd unit that manages the main snap communication socket"
  systemd:
    name: snapd.socket
    state: enabled

- name: "Create a symbolic link between /var/lib/snapd/snap and /snap to enable classic snap support"
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
