---
dependency:
  name: gilt
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos
    image: centos:7
  - name: ubuntu
    image: ubuntu:18.04
  - name: archlinux
    image: archlinux/base

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
