---
- name: "Create group 'wheel'"
  group:
    name: wheel
    state: present

- name: Allow members of group 'wheel' to execute any command
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'

- name: "Create user {{ user_login }}"
  user:
    create_home: true

    generate_ssh_key: true
    # Add a comment to the end of ssh key
    ssh_key_comment: "{{ user_email }}"

    name: "{{ user_login }}"
    password: ""
    # Add user to sudoers
    group: wheel
    append: true
    # Add GECOS comment
    comment: "{{ user_name }}"

    state: present
  register: create_user

- name: "Force user {{ user_login }} to change password on first login"
  command: chage -d 0 {{ user_login }}
  when: create_user.changed
