---
- include_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: install-arch.yml
  when: ansible_os_family == 'Archlinux'

- name: "Copy '.vimrc' file into '/home/{{ user.login }}/'"
  copy:
    owner: "{{ user.login }}"
    src: "{{ role_path }}/files/.vimrc"
    dest: "/home/{{ user.login }}/"

- name: "Create directory for vim-plug"
  file:
    path: "/home/{{ user.login }}/.vim/autoload/"
    state: directory
  become: true
  become_user: "{{ user.login }}"

- name: "Download vim-plug to '~/.vim' directory"
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "/home/{{ user.login }}/.vim/autoload/plug.vim"
    owner: "{{ user.login }}"
    # Redownload the file on every try
    force: true

- name: "Install all vim plugins"
  command: >
    vim -E -s -c \"source /home/{{ user.login }}/.vimrc\"
    +PlugInstall +qall -V
  args:
    creates: "/home/{{ user.login }}/.vim/plugged"
  ignore_errors: true
  become: true
  become_user: "{{ user.login }}"

- name: "Set global git editor to: vim"
  git_config:
    name: core.editor
    scope: global
    value: vim
  become: true
  become_user: "{{ user.login }}"
