---
galaxy_info:
  role_name: mc
  author: Alex Chernevskiy
  description: Ansible role which installs Midnight Commander.

  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: centos
      versions:
        - 7
    - name: ubuntu
      versions:
        - 18.04
    - name: archlinux
      versions:
        - all
